baseURL: 'https://5kbpers.github.io'
languageCode: 'en-us'
title: '5kbpers'
theme: 'papermod'

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  keywords: [Blog, Portfolio]
  author: "5kbpers"
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  label:
    text: "5kBâ‡…(Draft)"

  profileMode:
    enabled: true # needs to be explicitly set
    title: Derek Tang (5kbpers)
    subtitle: "Enthusiast of [Database, Web3, Rust]"
    imageUrl: "avatar.jpeg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: 5kbpers
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags
      - name: About me
        url: about

  socialIcons:
    - name: "twitter"
      url: "https://twitter.com/5kbpers1"
    - name: "github"
      url: "https://github.com/5kbpers"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/minghua-tang-60b247181/"
    - name: "email"
      url: "mailto://hustmh@gmail.com"

